theme: jekyll-theme-dinky
title: Multi-Resolution Attenuation Tomography
description: >-
  MuRAT is an open-source MATLAB package for 3D seismic attenuation, scattering
  and absorption tomography using body and coda waves at multiple frequencies.
